### ISSUE TITLE
Add responsiveness to the homepage

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/synd_dev#3]

**Comment by drockparashar** [comment]
I would like to work on this issue, please assign this to me.

**Comment by Gaurav-Verma07** [comment]
Please write mobile first css

**Comment by Gaurav-Verma07** [comment]
what's the progress?

**Comment by drockparashar** [comment]
I am currently learning mantine, then I will try to update UI.

**Comment by drockparashar** [comment]
I am having issue running this project on my local environment according to the steps in CONTRIBUTION.md

![image](https://github.com/Gaurav-Verma07/synd_dev/assets/118686637/f528b3af-6acb-4601-8f2c-f6c363a6692f)

**Comment by Gaurav-Verma07** [comment]
use `npm install --force`

**Comment by drockparashar** [comment]
Thank you. I will work on it right away.
